### PR TITLE
Update FeedForwardNetExperiment.cs

### PR DESCRIPTION
**Pull request by MukitCSTE**
1. Have added HTM classifier at layer2
2. Add mechanism for SP+TM training process at layer 2 
3. Generate output and accuracy test

### CODE REVIEW

**Comment by ddobric** [comment]
No PRs are accepted in this project stage.

**Comment by MukitCSTE** [comment]
Propose changes actually is only for the Unit Test file for FeedForwardNetExperiment

https://github.com/MukitCSTE/neocortexapi/blob/master/NeoCortexApi/UnitTestsProject/CortexNetworkTests/FeedForwardNetExperiment.cs

**Comment by MukitCSTE** [comment]
It's actually the propose changes unit test fiI am sorry but It's actually the request for reviewing the Proposed changes only for the Unit Test file for FeedForwardNetExperiment. Anyway, I just shared the URL of my forked branch link bellow so that you can check and give feedback. Thank you

https://github.com/MukitCSTE/neocortexapi/blob/master/NeoCortexApi/UnitTestsProject/CortexNetworkTests/FeedForwardNetExperiment.csle for the  FeedForwardNetExperiment

**Comment by MukitCSTE** [comment]
I am sorry but It's actually the request for reviewing the Proposed changes only for the Unit Test file for FeedForwardNetExperiment. Anyway, I just shared the URL of my forked branch link below so that you can check and give feedback. Thank you

https://github.com/MukitCSTE/neocortexapi/blob/master/NeoCortexApi/UnitTestsProject/CortexNetworkTests/FeedForwardNetExperiment.cs

**Pull request closed without merging**
